application: stg-football
version: 2
runtime: go
api_version: go1

handlers:
- url: /index\.css
  static_files: index.css
  upload: index\.css

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts
  mime_type: application/octet-stream

- url: /javascripts/
  static_dir: javascripts
  mime_type: application/javascript

- url: /stylesheets/
  static_dir: stylesheets

- url: /.*
  script: _go_app
